<?php $this->widget('yiiwheels.widgets.grid.WhGridView',array(
        'id'=>'sale-daily-profit-grid',
        'fixedHeader' => true,
        'responsiveTable' => true,
        'type'=>TbHtml::GRID_TYPE_BORDERED,
	'dataProvider'=>$report->saledailyprofit(),
        'summaryText' =>'<p class="text-info" align="left">' . Yii::t('app','Daily Profit') . Yii::t('app','From') . ':  ' . $from_date . '  ' . Yii::t('app','To') . ':  ' . $to_date . '</p>',
	'columns'=>array(
		array('name'=>'date_report',
                      'header'=>Yii::t('app','Date'), 
                      'value'=>'$data["date_report"]',
                ),
                array('name'=>'sub_total',
                      'header'=>Yii::t('app','Sub Total'),
                      'value' =>'number_format($data["sub_total"],Yii::app()->shoppingCart->getDecimalPlace(), ".", ",")',
                      'htmlOptions'=>array('style' => 'text-align: right;'),
                      'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                      'footer'=>Yii::app()->settings->get('site', 'currencySymbol')  . number_format($report->saleDailyProfitTotals()[0],Yii::app()->shoppingCart->getDecimalPlace(), ".", ","),
                      'footerHtmlOptions'=>array('style' => 'text-align: right;'),
                ),
		array('name'=>'profit',
                      'header'=>Yii::t('app','Profit'), 
                      'htmlOptions'=>array('style' => 'text-align: right;'),
                      'headerHtmlOptions'=>array('style' => 'text-align: right;'),
                      'value' =>'number_format($data["profit"],Yii::app()->shoppingCart->getDecimalPlace(), ".", ",")',
                      'footer'=>Yii::app()->settings->get('site', 'currencySymbol')  . number_format($report->saleDailyProfitTotals()[2],Yii::app()->shoppingCart->getDecimalPlace(), ".", ","),
                      'footerHtmlOptions'=>array('style' => 'text-align: right;'),
                ),
                array('name'=>'margin',
                      'header'=>Yii::t('app','Margin'),
                      'htmlOptions'=>array('style' => 'text-align: right;'),
                      'headerHtmlOptions'=>array('style' => 'text-align: right;'),  
                      'value'=>'$data["margin"] . "%"',
                ),
	),
)); ?>