<?php $this->widget('yiiwheels.widgets.grid.WhGridView',array(
        'id'=>'top-product-grid',
        'fixedHeader' => true,
        'responsiveTable' => true,
        'type'=>TbHtml::GRID_TYPE_BORDERED,
	'dataProvider'=>$report->topproduct(),
        'summaryText' =>'<p class="text-info" align="left">' . Yii::t('app','Top 10 Products') . Yii::t('app','From') . ':   ' . $from_date . '  ' . Yii::t('app','To') . ':   ' . $to_date . '   ' . Yii::t('app','Ranked by quantity') .'</p>', 
	'columns'=>array(
                array('name'=>'rank',
                      'header'=>Yii::t('app','Rank'),
                      'value'=>'$data["rank"]',
                ),
                array('name'=>'item_name',
                      'header'=>Yii::t('app','Item Name'),  
                      'value'=>'$data["item_name"]',
                ),
                array('name'=>'qty',
                      'header'=>Yii::t('app','Quantity'),  
                      'value'=>'$data["qty"]',
                      //'footer'=>$report->paymentTotalQty() ,
                ),
		array('name'=>'amount',
                      'header'=>Yii::t('app','Amount'),  
                      'value'=>'$data["amount"]',
                      //'footer'=>Yii::app()->getNumberFormatter()->formatCurrency($report->paymentTotalAmount(),'USD'),
                ),
	),
)); ?>